module.exports={
    chan:[
        [   {id:"ch1",prop:"ChState",arg:"",cb:null,method:"get"},
            {id:"ch1",prop:"BWLimit",arg:"",cb:null,method:"get"},
            {id:"ch1",prop:"COUPling",arg:"",cb:null,method:"get"},
            {id:"ch1",prop:"VerSCALe",arg:"",cb:null,method:"get"},
            {id:"ch1",prop:"VerPOSition",arg:"",cb:null,method:"get"},
            {id:"ch1",prop:"VerEXPand",arg:"",cb:null,method:"get"},
            {id:"ch1",prop:"INVert",arg:"",cb:null,method:"get"},
            {id:"ch1",prop:"PROBe_RATio",arg:"",cb:null,method:"get"},
            {id:"ch1",prop:"PROBe_Type",arg:"",cb:null,method:"get"},
            {id:"ch1",prop:"DESKew",arg:"",cb:null,method:"get"}
        ],[
            {id:"ch2",prop:"ChState",arg:"",cb:null,method:"get"},
            {id:"ch2",prop:"BWLimit",arg:"",cb:null,method:"get"},
            {id:"ch2",prop:"COUPling",arg:"",cb:null,method:"get"},
            {id:"ch2",prop:"VerSCALe",arg:"",cb:null,method:"get"},
            {id:"ch2",prop:"VerPOSition",arg:"",cb:null,method:"get"},
            {id:"ch2",prop:"VerEXPand",arg:"",cb:null,method:"get"},
            {id:"ch2",prop:"INVert",arg:"",cb:null,method:"get"},
            {id:"ch2",prop:"PROBe_RATio",arg:"",cb:null,method:"get"},
            {id:"ch2",prop:"PROBe_Type",arg:"",cb:null,method:"get"},
            {id:"ch2",prop:"DESKew",arg:"",cb:null,method:"get"}
        ],[
            {id:"ch3",prop:"BWLimit",arg:"",cb:null,method:"get"},
            {id:"ch3",prop:"COUPling",arg:"",cb:null,method:"get"},
            {id:"ch3",prop:"VerSCALe",arg:"",cb:null,method:"get"},
            {id:"ch3",prop:"VerPOSition",arg:"",cb:null,method:"get"},
            {id:"ch3",prop:"VerEXPand",arg:"",cb:null,method:"get"},
            {id:"ch3",prop:"INVert",arg:"",cb:null,method:"get"},
            {id:"ch3",prop:"PROBe_RATio",arg:"",cb:null,method:"get"},
            {id:"ch3",prop:"PROBe_Type",arg:"",cb:null,method:"get"},
            {id:"ch3",prop:"DESKew",arg:"",cb:null,method:"get"}
        ],[
            {id:"ch4",prop:"ChState",arg:"",cb:null,method:"get"},
            {id:"ch4",prop:"BWLimit",arg:"",cb:null,method:"get"},
            {id:"ch4",prop:"COUPling",arg:"",cb:null,method:"get"},
            {id:"ch4",prop:"VerSCALe",arg:"",cb:null,method:"get"},
            {id:"ch4",prop:"VerPOSition",arg:"",cb:null,method:"get"},
            {id:"ch4",prop:"VerEXPand",arg:"",cb:null,method:"get"},
            {id:"ch4",prop:"INVert",arg:"",cb:null,method:"get"},
            {id:"ch4",prop:"PROBe_RATio",arg:"",cb:null,method:"get"},
            {id:"ch4",prop:"PROBe_Type",arg:"",cb:null,method:"get"},
            {id:"ch4",prop:"DESKew",arg:"",cb:null,method:"get"}
        ]
    ],
    sys:[
        {id:"trig",prop:"TrigType",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigSource",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigHighLevel",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigLowLevel",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigEdgeSlop",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigCouple",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigNoiseRej",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigMode",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigHoldoff",arg:"",cb:null,method:"get"},

        {id:"trig",prop:"TrigType",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigDelayType",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigDelayEvent",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigDelayType",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigDelaySlop",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigDelayLevel",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigDelayTime",arg:"",cb:null,method:"get"},

    // {id:"trig",prop:"TrigPulseWidthPolarity",arg:"NEGATIVE"},
    // {id:"trig",prop:"TrigPulseWidthWhen",arg:"EQUAL"},
    // {id:"trig",prop:"TrigPulseWidthTime",arg:"1E-1"},
    // {id:"trig",prop:"TrigRuntPolarity",arg:"EITHER"},
    // {id:"trig",prop:"TrigRuntWhen",arg:"UNEQUAL"},
    // {id:"trig",prop:"TrigRuntTime",arg:"1E-1"},
    // {id:"trig",prop:"TrigRiseFallSlop",arg:"EITHER"},
    // {id:"trig",prop:"TrigRiseFallWhen",arg:"LESSTHAN"},
    // {id:"trig",prop:"TrigRiseFallTime",arg:"1E-1"},
    // {id:"trig",prop:"TrigVideoType",arg:"NTSC"},
    // {id:"trig",prop:"TrigVideoField",arg:"FIELD2"},
    // {id:"trig",prop:"TrigVideoLine",arg:"262"},
    // {id:"trig",prop:"TrigVideoPolarity",arg:"NEGATIVE"},
    // {id:"trig",prop:"TrigALT",arg:"OFF"},
    // {id:"trig",prop:"TrigExtProbeType",arg:"CURRENT"},
    // {id:"trig",prop:"TrigExtProbeRatio",arg:"1E+0"},
        {id:"trig",prop:"TrigType",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigTimeoutTime",arg:"",cb:null,method:"get"},
        {id:"trig",prop:"TrigTimeoutWhen",arg:"",cb:null,method:"get"},
//Acquire
        {id:"acq",prop:"AcqRecLength",arg:"",cb:null,method:"get"},
        {id:"acq",prop:"AcqMode",arg:"",cb:null,method:"get"},
        {id:"acq",prop:"AcqAverage",arg:"",cb:null,method:"get"},
//horizontal
        {id:"hor",prop:"HorMode",arg:"",cb:null,method:"get"},
        {id:"hor",prop:"HorScale",arg:"",cb:null,method:"get"},
        {id:"hor",prop:"HorPosition",arg:"",cb:null,method:"get"},
        {id:"hor",prop:"HorExpand",arg:"",cb:null,method:"get"},
        {id:"hor",prop:"HorMode",arg:"",cb:null,method:"get"},
        {id:"hor",prop:"HorZoomScale",arg:"",cb:null,method:"get"},
        {id:"hor",prop:"HorZoomPosition",arg:"",cb:null,method:"get"},
//math
        {id:"math",prop:"MathDisp",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathType",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathDualSour1",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathDualSour2",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathDualOper",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathDualScale",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathDualPos",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathType",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathFftWin",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathFftSource",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathFftMag",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathFftVerPos",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathFftVerScale",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathFftHorPos",arg:"",cb:null,method:"get"},
        {id:"math",prop:"MathFftHorScale",arg:"",cb:null,method:"get"}

        // {id:"meas1",prop:"MeasureState",arg:"ON"},
        // {id:"meas1",prop:"StatisticMode",arg:"ON"},
        // //{id:"meas1",prop:"StatisticReset",arg:""},
        // {id:"meas1",prop:"MeasureSource1",arg:"CH1"},
        // {id:"meas1",prop:"MeasureSource2",arg:"CH2"},
        // {id:"meas1",prop:"MeasureType",arg:"PK2pk"},
    ]
}

